### ISSUE TITLE
write_network_to_db ignores overwrite=True and throws and duplicate network error.

### ISSUE THREAD

**Issue by vogt31337** [e2nIEE/pandahub#64]
* pandahub version: ~0.3.4
* Python version: 3.11
* Operating System: ubuntu

### Description

Trying to write the same network twice with overwrite=True results in an duplicate network error.

### What I Did

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/XXX.py", line 125, in persist_to_pandahub
    document_id = self.ph_api.write_network_to_db(net=net, name=name, overwrite=True, skip_results=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pandahub/lib/PandaHub.py", line 1086, in write_network_to_db
    if self._network_with_name_exists(name, db):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pandahub/lib/PandaHub.py", line 1184, in _network_with_name_exists
    return self._get_id_from_name(name, db) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pandahub/lib/PandaHub.py", line 1180, in _get_id_from_name
    raise PandaHubError("Duplicate Network!")
pandahub.lib.PandaHub.PandaHubError: Duplicate Network!

**Comment by jthurner** [comment]
Can you check if you have two documents in the _networks collection with the same name?

**Comment by vogt31337** [comment]
more less solved. Error came because of a race condition corrupting the database...
